/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import inc.config;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Dzakiya
 */
public class bpKasir extends javax.swing.JFrame {

    Connection conn = config.Conn();
    Statement st;
    ResultSet rs;
    public static int id;

    private void tampilSupp() {
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("ID");
        model.addColumn("Nama");
        model.addColumn("Alamat");
        model.addColumn("No Telp");

        try {
            String sql = "SELECT * FROM SUPPLIER";
            st = conn.createStatement();
            rs = st.executeQuery(sql);

            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getString("ID_SUPPLIER"), rs.getString("NAMA_SUPPLIER"), rs.getString("ALAMAT_SUPPLIER"), rs.getString("NO_TELP_SUPPLIER")

                });
            }
            tbSupp.setModel(model);

        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }

    private void tampilCust() {
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("ID");
        model.addColumn("Nama");
        model.addColumn("Alamat");
        model.addColumn("No Telp");

        try {
            String sql = "SELECT * FROM PELANGGAN";
            st = conn.createStatement();
            rs = st.executeQuery(sql);

            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getString("ID_PELANGGAN"), rs.getString("NAMA_PELANGGAN"), rs.getString("ALAMAT_PELANGGAN"), rs.getString("NO_TELP_PELANGGAN")

                });
            }
            tbCust.setModel(model);

        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }

    private void tampilBuku() {
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("Tanggal Masuk");
        model.addColumn("ID BUKU");
        model.addColumn("ISBN");
        model.addColumn("Judul");
        model.addColumn("Penulis");
        model.addColumn("Stok");
        model.addColumn("Harga");
        model.addColumn("Kategori");
        model.addColumn("Penerbit");
        model.addColumn("Tahun Terbit");
        model.addColumn("Rak");

        try {
            String sql = "SELECT * FROM BUKU";
            st = conn.createStatement();
            rs = st.executeQuery(sql);

            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getString("TANGGAL_MASUK"), rs.getString("ID_BUKU"), rs.getString("ISBN"), rs.getString("JUDUL"), rs.getString("ID_PENULIS"), rs.getString("STOK"), rs.getString("HARGA"), rs.getString("ID_KATEGORI"), rs.getString("ID_PENERBIT"), rs.getString("TAHUN_TERBIT"), rs.getString("RAK")

                });
            }
            tbBuku.setModel(model);

        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }

    private void clear() {
        tfIDSupp.setText("");
        tfNamaSupp.setText("");
        tfAlamatSupp.setText("");
        tfNoSupp.setText("");
        tfIDCust.setText("");
        tfNamaCust.setText("");
        tfAlamatCust.setText("");
        tfNoCust.setText("");
        tfIDBuku.setText("");
        tfIDPenulis.setText("");
        tfIDPenerbit.setText("");
        tfIDKategori.setText("");
        tfISBN.setText("");
        tfJudulBuku.setText("");
        tfStok.setText("");
        tfRak.setText("");
        tfHarga.setText("");

    }

    public bpKasir() {
        initComponents();
        ID.setText(String.valueOf(bpLogin.getID()));
        tampilBuku();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        HEAD = new javax.swing.JPanel();
        head = new javax.swing.JLabel();
        ID = new javax.swing.JLabel();
        LEFT = new javax.swing.JPanel();
        btnBuku = new javax.swing.JButton();
        btnCust = new javax.swing.JButton();
        btnSupp = new javax.swing.JButton();
        btnJual = new javax.swing.JButton();
        btnBeli = new javax.swing.JButton();
        btnReport = new javax.swing.JButton();
        logout = new javax.swing.JButton();
        mainPanel = new javax.swing.JPanel();
        panelBuku = new javax.swing.JPanel();
        lBuku = new javax.swing.JLabel();
        lIDBuku = new javax.swing.JLabel();
        lNamaCust1 = new javax.swing.JLabel();
        lAlamatCust1 = new javax.swing.JLabel();
        lNoCust1 = new javax.swing.JLabel();
        tfIDBuku = new javax.swing.JTextField();
        tfHarga = new javax.swing.JTextField();
        btnSimpanBuku = new javax.swing.JButton();
        btnUbahBuku = new javax.swing.JButton();
        btnHapusBuku = new javax.swing.JButton();
        btnResetBuku = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        tbBuku = new javax.swing.JTable();
        tfSearchBuku = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        lNoCust2 = new javax.swing.JLabel();
        lNoCust3 = new javax.swing.JLabel();
        lNoCust4 = new javax.swing.JLabel();
        lIDBuku1 = new javax.swing.JLabel();
        lNoCust5 = new javax.swing.JLabel();
        lNoCust6 = new javax.swing.JLabel();
        tfISBN = new javax.swing.JTextField();
        tfStok = new javax.swing.JTextField();
        tfIDPenulis = new javax.swing.JTextField();
        tfJudulBuku = new javax.swing.JTextField();
        tfIDKategori = new javax.swing.JTextField();
        tfIDPenerbit = new javax.swing.JTextField();
        tahunterbit = new com.toedter.calendar.JYearChooser();
        tanggalmasuk = new com.toedter.calendar.JDateChooser();
        lNoCust7 = new javax.swing.JLabel();
        tfRak = new javax.swing.JTextField();
        panelCust = new javax.swing.JPanel();
        lCust = new javax.swing.JLabel();
        lIDCust = new javax.swing.JLabel();
        lNamaCust = new javax.swing.JLabel();
        lAlamatCust = new javax.swing.JLabel();
        lNoCust = new javax.swing.JLabel();
        tfIDCust = new javax.swing.JTextField();
        tfNamaCust = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        tfAlamatCust = new javax.swing.JTextArea();
        tfNoCust = new javax.swing.JTextField();
        btnSimpanCust = new javax.swing.JButton();
        btnUbahCust = new javax.swing.JButton();
        btnHapusCust = new javax.swing.JButton();
        btnResetCust = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        tbCust = new javax.swing.JTable();
        tfSearchCust = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        panelSupp = new javax.swing.JPanel();
        lSupp = new javax.swing.JLabel();
        lID = new javax.swing.JLabel();
        lNama = new javax.swing.JLabel();
        lAlamat = new javax.swing.JLabel();
        lNo = new javax.swing.JLabel();
        tfIDSupp = new javax.swing.JTextField();
        tfNamaSupp = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tfAlamatSupp = new javax.swing.JTextArea();
        tfNoSupp = new javax.swing.JTextField();
        btnSimpan = new javax.swing.JButton();
        btnUbah = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbSupp = new javax.swing.JTable();
        tfSearch = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        panelReport = new javax.swing.JPanel();
        lReport = new javax.swing.JLabel();
        panelTJ = new javax.swing.JPanel();
        lTJ = new javax.swing.JLabel();
        panelTB = new javax.swing.JPanel();
        lTB = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("BUKUPEDIA Kasir");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        HEAD.setBackground(new java.awt.Color(48, 58, 82));

        head.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        head.setForeground(new java.awt.Color(204, 204, 204));
        head.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        head.setIcon(new javax.swing.ImageIcon(getClass().getResource("/views/bpputih50.png"))); // NOI18N
        head.setText("BUKUPEDIA Kasir");

        ID.setFont(new java.awt.Font("Open Sans", 1, 12)); // NOI18N
        ID.setForeground(new java.awt.Color(204, 204, 204));
        ID.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        ID.setText("ID");

        javax.swing.GroupLayout HEADLayout = new javax.swing.GroupLayout(HEAD);
        HEAD.setLayout(HEADLayout);
        HEADLayout.setHorizontalGroup(
            HEADLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HEADLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(head, javax.swing.GroupLayout.PREFERRED_SIZE, 464, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(194, 194, 194)
                .addComponent(ID, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );
        HEADLayout.setVerticalGroup(
            HEADLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HEADLayout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addGroup(HEADLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(head)
                    .addComponent(ID))
                .addGap(13, 13, 13))
        );

        LEFT.setBackground(new java.awt.Color(204, 204, 204));
        LEFT.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 6, 6, 0, new java.awt.Color(48, 58, 82)));
        LEFT.setLayout(new java.awt.GridLayout(7, 1, 1, 4));

        btnBuku.setBackground(new java.awt.Color(204, 204, 204));
        btnBuku.setFont(new java.awt.Font("Open Sans", 1, 12)); // NOI18N
        btnBuku.setForeground(new java.awt.Color(48, 58, 82));
        btnBuku.setIcon(new javax.swing.ImageIcon(getClass().getResource("/views/buku20.png"))); // NOI18N
        btnBuku.setText("Buku");
        btnBuku.setBorder(null);
        btnBuku.setIconTextGap(10);
        btnBuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBukuActionPerformed(evt);
            }
        });
        LEFT.add(btnBuku);

        btnCust.setBackground(new java.awt.Color(204, 204, 204));
        btnCust.setFont(new java.awt.Font("Open Sans", 1, 12)); // NOI18N
        btnCust.setForeground(new java.awt.Color(48, 58, 82));
        btnCust.setIcon(new javax.swing.ImageIcon(getClass().getResource("/views/cust20.png"))); // NOI18N
        btnCust.setText("Customer");
        btnCust.setBorder(null);
        btnCust.setIconTextGap(10);
        btnCust.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCustActionPerformed(evt);
            }
        });
        LEFT.add(btnCust);

        btnSupp.setBackground(new java.awt.Color(204, 204, 204));
        btnSupp.setFont(new java.awt.Font("Open Sans", 1, 12)); // NOI18N
        btnSupp.setForeground(new java.awt.Color(48, 58, 82));
        btnSupp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/views/supp20.png"))); // NOI18N
        btnSupp.setText("Supplier");
        btnSupp.setBorder(null);
        btnSupp.setIconTextGap(10);
        btnSupp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuppActionPerformed(evt);
            }
        });
        LEFT.add(btnSupp);

        btnJual.setBackground(new java.awt.Color(204, 204, 204));
        btnJual.setFont(new java.awt.Font("Open Sans", 1, 12)); // NOI18N
        btnJual.setForeground(new java.awt.Color(48, 58, 82));
        btnJual.setIcon(new javax.swing.ImageIcon(getClass().getResource("/views/tjual20.png"))); // NOI18N
        btnJual.setText("Transaksi Penjualan");
        btnJual.setBorder(null);
        btnJual.setIconTextGap(10);
        btnJual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJualActionPerformed(evt);
            }
        });
        LEFT.add(btnJual);

        btnBeli.setBackground(new java.awt.Color(204, 204, 204));
        btnBeli.setFont(new java.awt.Font("Open Sans", 1, 12)); // NOI18N
        btnBeli.setForeground(new java.awt.Color(48, 58, 82));
        btnBeli.setIcon(new javax.swing.ImageIcon(getClass().getResource("/views/tbeli20.png"))); // NOI18N
        btnBeli.setText("Transaksi Pembelian");
        btnBeli.setBorder(null);
        btnBeli.setIconTextGap(10);
        btnBeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBeliActionPerformed(evt);
            }
        });
        LEFT.add(btnBeli);

        btnReport.setBackground(new java.awt.Color(204, 204, 204));
        btnReport.setFont(new java.awt.Font("Open Sans", 1, 12)); // NOI18N
        btnReport.setForeground(new java.awt.Color(48, 58, 82));
        btnReport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/views/report20.png"))); // NOI18N
        btnReport.setText("Laporan");
        btnReport.setBorder(null);
        btnReport.setIconTextGap(10);
        btnReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportActionPerformed(evt);
            }
        });
        LEFT.add(btnReport);

        logout.setBackground(new java.awt.Color(204, 204, 204));
        logout.setFont(new java.awt.Font("Open Sans", 1, 12)); // NOI18N
        logout.setForeground(new java.awt.Color(48, 58, 82));
        logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/views/logout.png"))); // NOI18N
        logout.setText("Log Out");
        logout.setBorder(null);
        logout.setIconTextGap(10);
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });
        LEFT.add(logout);

        mainPanel.setBackground(new java.awt.Color(204, 204, 204));
        mainPanel.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 3, 3, 3, new java.awt.Color(48, 58, 82)));
        mainPanel.setLayout(new java.awt.CardLayout());

        panelBuku.setBackground(new java.awt.Color(204, 204, 204));
        panelBuku.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 3, 3, 3, new java.awt.Color(48, 58, 82)));

        lBuku.setBackground(new java.awt.Color(48, 58, 82));
        lBuku.setFont(new java.awt.Font("Open Sans", 1, 18)); // NOI18N
        lBuku.setForeground(new java.awt.Color(48, 58, 82));
        lBuku.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lBuku.setText("Data Buku");

        lIDBuku.setFont(new java.awt.Font("Open Sans", 1, 12)); // NOI18N
        lIDBuku.setForeground(new java.awt.Color(48, 58, 82));
        lIDBuku.setText("Tanggal Masuk");

        lNamaCust1.setFont(new java.awt.Font("Open Sans", 1, 12)); // NOI18N
        lNamaCust1.setForeground(new java.awt.Color(48, 58, 82));
        lNamaCust1.setText("ISBN");

        lAlamatCust1.setFont(new java.awt.Font("Open Sans", 1, 12)); // NOI18N
        lAlamatCust1.setForeground(new java.awt.Color(48, 58, 82));
        lAlamatCust1.setText("Judul");

        lNoCust1.setFont(new java.awt.Font("Open Sans", 1, 12)); // NOI18N
        lNoCust1.setForeground(new java.awt.Color(48, 58, 82));
        lNoCust1.setText("ID Penulis");

        tfIDBuku.setBackground(new java.awt.Color(204, 204, 204));
        tfIDBuku.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N
        tfIDBuku.setForeground(new java.awt.Color(48, 58, 82));
        tfIDBuku.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(48, 58, 82)));

        tfHarga.setBackground(new java.awt.Color(204, 204, 204));
        tfHarga.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N
        tfHarga.setForeground(new java.awt.Color(48, 58, 82));
        tfHarga.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(48, 58, 82)));

        btnSimpanBuku.setBackground(new java.awt.Color(48, 58, 82));
        btnSimpanBuku.setFont(new java.awt.Font("Open Sans", 1, 12)); // NOI18N
        btnSimpanBuku.setText("Simpan");
        btnSimpanBuku.setBorder(null);
        btnSimpanBuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanBukuActionPerformed(evt);
            }
        });

        btnUbahBuku.setBackground(new java.awt.Color(48, 58, 82));
        btnUbahBuku.setFont(new java.awt.Font("Open Sans", 1, 12)); // NOI18N
        btnUbahBuku.setText("Ubah");
        btnUbahBuku.setBorder(null);
        btnUbahBuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbahBukuActionPerformed(evt);
            }
        });

        btnHapusBuku.setBackground(new java.awt.Color(48, 58, 82));
        btnHapusBuku.setFont(new java.awt.Font("Open Sans", 1, 12)); // NOI18N
        btnHapusBuku.setText("Hapus");
        btnHapusBuku.setBorder(null);
        btnHapusBuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusBukuActionPerformed(evt);
            }
        });

        btnResetBuku.setBackground(new java.awt.Color(48, 58, 82));
        btnResetBuku.setFont(new java.awt.Font("Open Sans", 1, 12)); // NOI18N
        btnResetBuku.setText("Reset");
        btnResetBuku.setBorder(null);
        btnResetBuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetBukuActionPerformed(evt);
            }
        });

        jScrollPane6.setBackground(new java.awt.Color(204, 204, 204));
        jScrollPane6.setForeground(new java.awt.Color(48, 58, 82));

        tbBuku.setBackground(new java.awt.Color(204, 204, 204));
        tbBuku.setFont(new java.awt.Font("Open Sans", 1, 12)); // NOI18N
        tbBuku.setForeground(new java.awt.Color(48, 58, 82));
        tbBuku.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tanggal Masuk", "ID Buku", "ISBN", "Judul", "Penulis", "Stok", "Harga", "Kategori", "Penerbit", "Tahun Terbit", "Rak"
            }
        ));
        tbBuku.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbBukuMouseClicked(evt);
            }
        });
        jScrollPane6.setViewportView(tbBuku);

        tfSearchBuku.setBackground(new java.awt.Color(204, 204, 204));
        tfSearchBuku.setFont(new java.awt.Font("Open Sans", 1, 12)); // NOI18N
        tfSearchBuku.setForeground(new java.awt.Color(48, 58, 82));
        tfSearchBuku.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(48, 58, 82)));
        tfSearchBuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfSearchBukuActionPerformed(evt);
            }
        });
        tfSearchBuku.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfSearchBukuKeyPressed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Open Sans", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(48, 58, 82));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/views/icons8_google_web_search_20px_2.png"))); // NOI18N
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jLabel4.setIconTextGap(1);

        lNoCust2.setFont(new java.awt.Font("Open Sans", 1, 12)); // NOI18N
        lNoCust2.setForeground(new java.awt.Color(48, 58, 82));
        lNoCust2.setText("ID Kategori");

        lNoCust3.setFont(new java.awt.Font("Open Sans", 1, 12)); // NOI18N
        lNoCust3.setForeground(new java.awt.Color(48, 58, 82));
        lNoCust3.setText("Penerbit");

        lNoCust4.setFont(new java.awt.Font("Open Sans", 1, 12)); // NOI18N
        lNoCust4.setForeground(new java.awt.Color(48, 58, 82));
        lNoCust4.setText("Tahun Terbit");

        lIDBuku1.setFont(new java.awt.Font("Open Sans", 1, 12)); // NOI18N
        lIDBuku1.setForeground(new java.awt.Color(48, 58, 82));
        lIDBuku1.setText("ID Buku");

        lNoCust5.setFont(new java.awt.Font("Open Sans", 1, 12)); // NOI18N
        lNoCust5.setForeground(new java.awt.Color(48, 58, 82));
        lNoCust5.setText("Stok");

        lNoCust6.setFont(new java.awt.Font("Open Sans", 1, 12)); // NOI18N
        lNoCust6.setForeground(new java.awt.Color(48, 58, 82));
        lNoCust6.setText("Harga");

        tfISBN.setBackground(new java.awt.Color(204, 204, 204));
        tfISBN.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N
        tfISBN.setForeground(new java.awt.Color(48, 58, 82));
        tfISBN.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(48, 58, 82)));

        tfStok.setBackground(new java.awt.Color(204, 204, 204));
        tfStok.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N
        tfStok.setForeground(new java.awt.Color(48, 58, 82));
        tfStok.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(48, 58, 82)));

        tfIDPenulis.setBackground(new java.awt.Color(204, 204, 204));
        tfIDPenulis.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N
        tfIDPenulis.setForeground(new java.awt.Color(48, 58, 82));
        tfIDPenulis.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(48, 58, 82)));

        tfJudulBuku.setBackground(new java.awt.Color(204, 204, 204));
        tfJudulBuku.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N
        tfJudulBuku.setForeground(new java.awt.Color(48, 58, 82));
        tfJudulBuku.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(48, 58, 82)));

        tfIDKategori.setBackground(new java.awt.Color(204, 204, 204));
        tfIDKategori.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N
        tfIDKategori.setForeground(new java.awt.Color(48, 58, 82));
        tfIDKategori.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(48, 58, 82)));

        tfIDPenerbit.setBackground(new java.awt.Color(204, 204, 204));
        tfIDPenerbit.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N
        tfIDPenerbit.setForeground(new java.awt.Color(48, 58, 82));
        tfIDPenerbit.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(48, 58, 82)));

        tahunterbit.setBackground(new java.awt.Color(204, 204, 204));
        tahunterbit.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(48, 58, 82)));

        tanggalmasuk.setBackground(new java.awt.Color(204, 204, 204));
        tanggalmasuk.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(48, 58, 82)));
        tanggalmasuk.setForeground(new java.awt.Color(48, 58, 82));
        tanggalmasuk.setDateFormatString("dd-MM-yyyy");
        tanggalmasuk.setFocusTraversalPolicyProvider(true);

        lNoCust7.setFont(new java.awt.Font("Open Sans", 1, 12)); // NOI18N
        lNoCust7.setForeground(new java.awt.Color(48, 58, 82));
        lNoCust7.setText("Rak");

        tfRak.setBackground(new java.awt.Color(204, 204, 204));
        tfRak.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N
        tfRak.setForeground(new java.awt.Color(48, 58, 82));
        tfRak.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(48, 58, 82)));

        javax.swing.GroupLayout panelBukuLayout = new javax.swing.GroupLayout(panelBuku);
        panelBuku.setLayout(panelBukuLayout);
        panelBukuLayout.setHorizontalGroup(
            panelBukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lBuku, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelBukuLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(panelBukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelBukuLayout.createSequentialGroup()
                        .addGroup(panelBukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelBukuLayout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addGroup(panelBukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lNamaCust1)
                                    .addComponent(lAlamatCust1)
                                    .addComponent(lNoCust1)
                                    .addComponent(lNoCust2)
                                    .addComponent(lIDBuku1)
                                    .addComponent(lIDBuku, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lNoCust5)
                                    .addComponent(lNoCust6)))
                            .addComponent(lNoCust3)
                            .addComponent(lNoCust7))
                        .addGap(26, 26, 26)
                        .addGroup(panelBukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(tfStok)
                            .addComponent(tfIDBuku, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfHarga, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfISBN, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfIDPenulis, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfJudulBuku, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfIDKategori, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelBukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(tfIDPenerbit, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(panelBukuLayout.createSequentialGroup()
                                    .addComponent(btnSimpanBuku, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnUbahBuku, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(panelBukuLayout.createSequentialGroup()
                                    .addComponent(btnHapusBuku, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnResetBuku, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(tfRak, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelBukuLayout.createSequentialGroup()
                                .addComponent(tanggalmasuk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(1, 1, 1))))
                    .addGroup(panelBukuLayout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addComponent(tahunterbit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lNoCust4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addGroup(panelBukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBukuLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfSearchBuku, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10))
        );
        panelBukuLayout.setVerticalGroup(
            panelBukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBukuLayout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(lBuku)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelBukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lIDBuku)
                    .addComponent(tanggalmasuk, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelBukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tfSearchBuku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4)))
                .addGap(12, 12, 12)
                .addGroup(panelBukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelBukuLayout.createSequentialGroup()
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54))
                    .addGroup(panelBukuLayout.createSequentialGroup()
                        .addGroup(panelBukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfIDBuku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lIDBuku1, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(13, 13, 13)
                        .addGroup(panelBukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lNamaCust1)
                            .addComponent(tfISBN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(panelBukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelBukuLayout.createSequentialGroup()
                                .addComponent(lAlamatCust1)
                                .addGap(12, 12, 12)
                                .addComponent(lNoCust1))
                            .addGroup(panelBukuLayout.createSequentialGroup()
                                .addComponent(tfJudulBuku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(11, 11, 11)
                                .addComponent(tfIDPenulis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(12, 12, 12)
                        .addGroup(panelBukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelBukuLayout.createSequentialGroup()
                                .addComponent(lNoCust5)
                                .addGap(12, 12, 12)
                                .addComponent(lNoCust6)
                                .addGap(12, 12, 12)
                                .addComponent(lNoCust2)
                                .addGap(12, 12, 12)
                                .addComponent(lNoCust3)
                                .addGap(18, 18, 18)
                                .addComponent(lNoCust7))
                            .addGroup(panelBukuLayout.createSequentialGroup()
                                .addComponent(tfStok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(tfHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(11, 11, 11)
                                .addComponent(tfIDKategori, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(tfIDPenerbit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(tfRak, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                        .addGroup(panelBukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lNoCust4)
                            .addComponent(tahunterbit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelBukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSimpanBuku, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnUbahBuku, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelBukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnHapusBuku, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnResetBuku, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15))))
        );

        mainPanel.add(panelBuku, "card2");

        panelCust.setBackground(new java.awt.Color(204, 204, 204));
        panelCust.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 3, 3, 3, new java.awt.Color(48, 58, 82)));

        lCust.setBackground(new java.awt.Color(48, 58, 82));
        lCust.setFont(new java.awt.Font("Open Sans", 1, 18)); // NOI18N
        lCust.setForeground(new java.awt.Color(48, 58, 82));
        lCust.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lCust.setText("Data Customer");

        lIDCust.setFont(new java.awt.Font("Open Sans", 1, 12)); // NOI18N
        lIDCust.setForeground(new java.awt.Color(48, 58, 82));
        lIDCust.setText("ID Customer");

        lNamaCust.setFont(new java.awt.Font("Open Sans", 1, 12)); // NOI18N
        lNamaCust.setForeground(new java.awt.Color(48, 58, 82));
        lNamaCust.setText("Nama");

        lAlamatCust.setFont(new java.awt.Font("Open Sans", 1, 12)); // NOI18N
        lAlamatCust.setForeground(new java.awt.Color(48, 58, 82));
        lAlamatCust.setText("Alamat");

        lNoCust.setFont(new java.awt.Font("Open Sans", 1, 12)); // NOI18N
        lNoCust.setForeground(new java.awt.Color(48, 58, 82));
        lNoCust.setText("No. Telp");

        tfIDCust.setBackground(new java.awt.Color(204, 204, 204));
        tfIDCust.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N
        tfIDCust.setForeground(new java.awt.Color(48, 58, 82));
        tfIDCust.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(48, 58, 82)));
        tfIDCust.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfIDCustActionPerformed(evt);
            }
        });

        tfNamaCust.setBackground(new java.awt.Color(204, 204, 204));
        tfNamaCust.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N
        tfNamaCust.setForeground(new java.awt.Color(48, 58, 82));
        tfNamaCust.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(48, 58, 82)));

        jScrollPane3.setBackground(new java.awt.Color(204, 204, 204));
        jScrollPane3.setBorder(null);
        jScrollPane3.setForeground(new java.awt.Color(48, 58, 82));

        tfAlamatCust.setBackground(new java.awt.Color(204, 204, 204));
        tfAlamatCust.setColumns(20);
        tfAlamatCust.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N
        tfAlamatCust.setForeground(new java.awt.Color(48, 58, 82));
        tfAlamatCust.setRows(5);
        tfAlamatCust.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(48, 58, 82)));
        jScrollPane3.setViewportView(tfAlamatCust);

        tfNoCust.setBackground(new java.awt.Color(204, 204, 204));
        tfNoCust.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N
        tfNoCust.setForeground(new java.awt.Color(48, 58, 82));
        tfNoCust.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(48, 58, 82)));

        btnSimpanCust.setBackground(new java.awt.Color(48, 58, 82));
        btnSimpanCust.setFont(new java.awt.Font("Open Sans", 1, 12)); // NOI18N
        btnSimpanCust.setText("Simpan");
        btnSimpanCust.setBorder(null);
        btnSimpanCust.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanCustActionPerformed(evt);
            }
        });

        btnUbahCust.setBackground(new java.awt.Color(48, 58, 82));
        btnUbahCust.setFont(new java.awt.Font("Open Sans", 1, 12)); // NOI18N
        btnUbahCust.setText("Ubah");
        btnUbahCust.setBorder(null);
        btnUbahCust.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbahCustActionPerformed(evt);
            }
        });

        btnHapusCust.setBackground(new java.awt.Color(48, 58, 82));
        btnHapusCust.setFont(new java.awt.Font("Open Sans", 1, 12)); // NOI18N
        btnHapusCust.setText("Hapus");
        btnHapusCust.setBorder(null);
        btnHapusCust.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusCustActionPerformed(evt);
            }
        });

        btnResetCust.setBackground(new java.awt.Color(48, 58, 82));
        btnResetCust.setFont(new java.awt.Font("Open Sans", 1, 12)); // NOI18N
        btnResetCust.setText("Reset");
        btnResetCust.setBorder(null);
        btnResetCust.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetCustActionPerformed(evt);
            }
        });

        jScrollPane4.setBackground(new java.awt.Color(204, 204, 204));
        jScrollPane4.setForeground(new java.awt.Color(48, 58, 82));

        tbCust.setBackground(new java.awt.Color(204, 204, 204));
        tbCust.setFont(new java.awt.Font("Open Sans", 1, 12)); // NOI18N
        tbCust.setForeground(new java.awt.Color(48, 58, 82));
        tbCust.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nama", "Alamat", "No Telp"
            }
        ));
        tbCust.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbCustMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tbCust);

        tfSearchCust.setBackground(new java.awt.Color(204, 204, 204));
        tfSearchCust.setFont(new java.awt.Font("Open Sans", 1, 12)); // NOI18N
        tfSearchCust.setForeground(new java.awt.Color(48, 58, 82));
        tfSearchCust.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(48, 58, 82)));
        tfSearchCust.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfSearchCustActionPerformed(evt);
            }
        });
        tfSearchCust.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfSearchCustKeyPressed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Open Sans", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(48, 58, 82));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/views/icons8_google_web_search_20px_2.png"))); // NOI18N
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jLabel2.setIconTextGap(1);

        javax.swing.GroupLayout panelCustLayout = new javax.swing.GroupLayout(panelCust);
        panelCust.setLayout(panelCustLayout);
        panelCustLayout.setHorizontalGroup(
            panelCustLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lCust, javax.swing.GroupLayout.DEFAULT_SIZE, 964, Short.MAX_VALUE)
            .addGroup(panelCustLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(panelCustLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lIDCust)
                    .addComponent(lNamaCust)
                    .addComponent(lAlamatCust)
                    .addComponent(lNoCust))
                .addGap(32, 32, 32)
                .addGroup(panelCustLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCustLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(tfNamaCust)
                        .addComponent(tfIDCust)
                        .addComponent(tfNoCust, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelCustLayout.createSequentialGroup()
                        .addComponent(btnSimpanCust, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnUbahCust, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelCustLayout.createSequentialGroup()
                        .addComponent(btnHapusCust, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnResetCust, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelCustLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCustLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfSearchCust, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27))
        );
        panelCustLayout.setVerticalGroup(
            panelCustLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCustLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lCust)
                .addGap(24, 24, 24)
                .addGroup(panelCustLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lIDCust)
                    .addComponent(tfIDCust, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfSearchCust, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelCustLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCustLayout.createSequentialGroup()
                        .addGroup(panelCustLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lNamaCust)
                            .addComponent(tfNamaCust, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelCustLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lAlamatCust)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(panelCustLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelCustLayout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(lNoCust))
                            .addGroup(panelCustLayout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(tfNoCust, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(panelCustLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSimpanCust, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnUbahCust, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelCustLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnHapusCust, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnResetCust, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(49, Short.MAX_VALUE))
        );

        mainPanel.add(panelCust, "card2");

        panelSupp.setBackground(new java.awt.Color(204, 204, 204));
        panelSupp.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 3, 3, 3, new java.awt.Color(48, 58, 82)));

        lSupp.setBackground(new java.awt.Color(48, 58, 82));
        lSupp.setFont(new java.awt.Font("Open Sans", 1, 18)); // NOI18N
        lSupp.setForeground(new java.awt.Color(48, 58, 82));
        lSupp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lSupp.setText("Data Supplier");

        lID.setFont(new java.awt.Font("Open Sans", 1, 12)); // NOI18N
        lID.setForeground(new java.awt.Color(48, 58, 82));
        lID.setText("ID Supplier");

        lNama.setFont(new java.awt.Font("Open Sans", 1, 12)); // NOI18N
        lNama.setForeground(new java.awt.Color(48, 58, 82));
        lNama.setText("Nama");

        lAlamat.setFont(new java.awt.Font("Open Sans", 1, 12)); // NOI18N
        lAlamat.setForeground(new java.awt.Color(48, 58, 82));
        lAlamat.setText("Alamat");

        lNo.setFont(new java.awt.Font("Open Sans", 1, 12)); // NOI18N
        lNo.setForeground(new java.awt.Color(48, 58, 82));
        lNo.setText("No. Telp");

        tfIDSupp.setBackground(new java.awt.Color(204, 204, 204));
        tfIDSupp.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N
        tfIDSupp.setForeground(new java.awt.Color(48, 58, 82));
        tfIDSupp.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(48, 58, 82)));
        tfIDSupp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfIDSuppActionPerformed(evt);
            }
        });

        tfNamaSupp.setBackground(new java.awt.Color(204, 204, 204));
        tfNamaSupp.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N
        tfNamaSupp.setForeground(new java.awt.Color(48, 58, 82));
        tfNamaSupp.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(48, 58, 82)));

        jScrollPane1.setBackground(new java.awt.Color(204, 204, 204));
        jScrollPane1.setBorder(null);
        jScrollPane1.setForeground(new java.awt.Color(48, 58, 82));

        tfAlamatSupp.setBackground(new java.awt.Color(204, 204, 204));
        tfAlamatSupp.setColumns(20);
        tfAlamatSupp.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N
        tfAlamatSupp.setForeground(new java.awt.Color(48, 58, 82));
        tfAlamatSupp.setRows(5);
        tfAlamatSupp.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(48, 58, 82)));
        jScrollPane1.setViewportView(tfAlamatSupp);

        tfNoSupp.setBackground(new java.awt.Color(204, 204, 204));
        tfNoSupp.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N
        tfNoSupp.setForeground(new java.awt.Color(48, 58, 82));
        tfNoSupp.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(48, 58, 82)));

        btnSimpan.setBackground(new java.awt.Color(48, 58, 82));
        btnSimpan.setFont(new java.awt.Font("Open Sans", 1, 12)); // NOI18N
        btnSimpan.setText("Simpan");
        btnSimpan.setBorder(null);
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        btnUbah.setBackground(new java.awt.Color(48, 58, 82));
        btnUbah.setFont(new java.awt.Font("Open Sans", 1, 12)); // NOI18N
        btnUbah.setText("Ubah");
        btnUbah.setBorder(null);
        btnUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbahActionPerformed(evt);
            }
        });

        btnHapus.setBackground(new java.awt.Color(48, 58, 82));
        btnHapus.setFont(new java.awt.Font("Open Sans", 1, 12)); // NOI18N
        btnHapus.setText("Hapus");
        btnHapus.setBorder(null);
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        btnReset.setBackground(new java.awt.Color(48, 58, 82));
        btnReset.setFont(new java.awt.Font("Open Sans", 1, 12)); // NOI18N
        btnReset.setText("Reset");
        btnReset.setBorder(null);
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        jScrollPane2.setBackground(new java.awt.Color(204, 204, 204));
        jScrollPane2.setForeground(new java.awt.Color(48, 58, 82));

        tbSupp.setBackground(new java.awt.Color(204, 204, 204));
        tbSupp.setFont(new java.awt.Font("Open Sans", 1, 12)); // NOI18N
        tbSupp.setForeground(new java.awt.Color(48, 58, 82));
        tbSupp.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nama", "Alamat", "No Telp"
            }
        ));
        tbSupp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbSuppMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbSupp);

        tfSearch.setBackground(new java.awt.Color(204, 204, 204));
        tfSearch.setFont(new java.awt.Font("Open Sans", 1, 12)); // NOI18N
        tfSearch.setForeground(new java.awt.Color(48, 58, 82));
        tfSearch.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(48, 58, 82)));
        tfSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfSearchActionPerformed(evt);
            }
        });
        tfSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfSearchKeyPressed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Open Sans", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(48, 58, 82));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/views/icons8_google_web_search_20px_2.png"))); // NOI18N
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jLabel1.setIconTextGap(1);

        javax.swing.GroupLayout panelSuppLayout = new javax.swing.GroupLayout(panelSupp);
        panelSupp.setLayout(panelSuppLayout);
        panelSuppLayout.setHorizontalGroup(
            panelSuppLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lSupp, javax.swing.GroupLayout.DEFAULT_SIZE, 964, Short.MAX_VALUE)
            .addGroup(panelSuppLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(panelSuppLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lID)
                    .addComponent(lNama)
                    .addComponent(lAlamat)
                    .addComponent(lNo))
                .addGap(39, 39, 39)
                .addGroup(panelSuppLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelSuppLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                        .addComponent(tfNamaSupp)
                        .addComponent(tfIDSupp)
                        .addComponent(tfNoSupp))
                    .addGroup(panelSuppLayout.createSequentialGroup()
                        .addComponent(btnSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnUbah, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelSuppLayout.createSequentialGroup()
                        .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelSuppLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSuppLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27))
        );
        panelSuppLayout.setVerticalGroup(
            panelSuppLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSuppLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lSupp)
                .addGap(24, 24, 24)
                .addGroup(panelSuppLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lID)
                    .addComponent(tfIDSupp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelSuppLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelSuppLayout.createSequentialGroup()
                        .addGroup(panelSuppLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lNama)
                            .addComponent(tfNamaSupp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelSuppLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lAlamat)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(panelSuppLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelSuppLayout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(lNo))
                            .addGroup(panelSuppLayout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(tfNoSupp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(panelSuppLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnUbah, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelSuppLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(49, Short.MAX_VALUE))
        );

        mainPanel.add(panelSupp, "card2");

        panelReport.setBackground(new java.awt.Color(204, 204, 204));
        panelReport.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 3, 3, 3, new java.awt.Color(48, 58, 82)));

        lReport.setBackground(new java.awt.Color(48, 58, 82));
        lReport.setFont(new java.awt.Font("Open Sans", 1, 18)); // NOI18N
        lReport.setForeground(new java.awt.Color(48, 58, 82));
        lReport.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lReport.setText("Laporan Transaksi");

        javax.swing.GroupLayout panelReportLayout = new javax.swing.GroupLayout(panelReport);
        panelReport.setLayout(panelReportLayout);
        panelReportLayout.setHorizontalGroup(
            panelReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lReport, javax.swing.GroupLayout.DEFAULT_SIZE, 964, Short.MAX_VALUE)
        );
        panelReportLayout.setVerticalGroup(
            panelReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelReportLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lReport)
                .addContainerGap(417, Short.MAX_VALUE))
        );

        mainPanel.add(panelReport, "card2");

        panelTJ.setBackground(new java.awt.Color(204, 204, 204));
        panelTJ.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 3, 3, 3, new java.awt.Color(48, 58, 82)));

        lTJ.setBackground(new java.awt.Color(48, 58, 82));
        lTJ.setFont(new java.awt.Font("Open Sans", 1, 18)); // NOI18N
        lTJ.setForeground(new java.awt.Color(48, 58, 82));
        lTJ.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lTJ.setText("Transaksi Penjualan");

        javax.swing.GroupLayout panelTJLayout = new javax.swing.GroupLayout(panelTJ);
        panelTJ.setLayout(panelTJLayout);
        panelTJLayout.setHorizontalGroup(
            panelTJLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lTJ, javax.swing.GroupLayout.DEFAULT_SIZE, 964, Short.MAX_VALUE)
        );
        panelTJLayout.setVerticalGroup(
            panelTJLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTJLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lTJ)
                .addContainerGap(425, Short.MAX_VALUE))
        );

        mainPanel.add(panelTJ, "card2");

        panelTB.setBackground(new java.awt.Color(204, 204, 204));
        panelTB.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 3, 3, 3, new java.awt.Color(48, 58, 82)));

        lTB.setBackground(new java.awt.Color(48, 58, 82));
        lTB.setFont(new java.awt.Font("Open Sans", 1, 18)); // NOI18N
        lTB.setForeground(new java.awt.Color(48, 58, 82));
        lTB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lTB.setText("Transaksi Pembelian");

        javax.swing.GroupLayout panelTBLayout = new javax.swing.GroupLayout(panelTB);
        panelTB.setLayout(panelTBLayout);
        panelTBLayout.setHorizontalGroup(
            panelTBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lTB, javax.swing.GroupLayout.DEFAULT_SIZE, 964, Short.MAX_VALUE)
        );
        panelTBLayout.setVerticalGroup(
            panelTBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTBLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lTB)
                .addContainerGap(417, Short.MAX_VALUE))
        );

        mainPanel.add(panelTB, "card2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(HEAD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(LEFT, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(HEAD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LEFT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBukuActionPerformed

        // remove panel
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();

        // add panel
        mainPanel.add(panelBuku);
        mainPanel.repaint();
        mainPanel.revalidate();

        tampilBuku();

    }//GEN-LAST:event_btnBukuActionPerformed

    private void btnJualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJualActionPerformed

        // remove panel
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();

        // add panel
        mainPanel.add(panelTJ);
        mainPanel.repaint();
        mainPanel.revalidate();

    }//GEN-LAST:event_btnJualActionPerformed

    private void btnReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportActionPerformed

        // remove panel
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();

        // add panel
        mainPanel.add(panelReport);
        mainPanel.repaint();
        mainPanel.revalidate();
    }//GEN-LAST:event_btnReportActionPerformed

    private void btnCustActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCustActionPerformed

        // remove panel
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();

        // add panel
        mainPanel.add(panelCust);
        mainPanel.repaint();
        mainPanel.revalidate();

        tampilCust();
    }//GEN-LAST:event_btnCustActionPerformed

    private void btnSuppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuppActionPerformed
        // TODO add your handling code here:
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();

        // add panel
        mainPanel.add(panelSupp);
        mainPanel.repaint();
        mainPanel.revalidate();

        tampilSupp();
    }//GEN-LAST:event_btnSuppActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        // TODO add your handling code here:
        int btnDialog = JOptionPane.YES_NO_OPTION;
        int rsDialog = JOptionPane.showConfirmDialog(this, "Yakin mau keluar?", "PERINGATAN", btnDialog);
        if (rsDialog == 0) {
            System.exit(0);
        } else {
        }
    }//GEN-LAST:event_logoutActionPerformed

    private void tfIDSuppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfIDSuppActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfIDSuppActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // Menyimpan Supp
        try {
            String sql = "INSERT INTO SUPPLIER VALUES ('" + tfIDSupp.getText() + "','" + tfNamaSupp.getText() + "','" + tfAlamatSupp.getText() + "','" + tfNoSupp.getText() + "')";
            st = conn.createStatement();
            st.executeUpdate(sql);
            JOptionPane.showMessageDialog(null, "Simpan Berhasil!");
            clear();
            tampilSupp();

        } catch (Exception e) {
            System.out.println(e.getMessage());
        }

    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahActionPerformed
        // Merubah Supp
        try {
            String sql = "UPDATE SUPPLIER SET NAMA_SUPPLIER = '" + tfNamaSupp.getText() + "', ALAMAT_SUPPLIER = '" + tfAlamatSupp.getText() + "', NO_TELP_SUPPLIER = '" + tfNoSupp.getText() + "' WHERE ID_SUPPLIER = '" + tfIDSupp.getText() + "'";
            st = conn.createStatement();
            st.executeUpdate(sql);
            JOptionPane.showMessageDialog(null, "Data telah diperbarui!");
            clear();
            tampilSupp();

        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_btnUbahActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // Menghapus Supp
        try {
            String sql = "DELETE FROM SUPPLIER WHERE ID_SUPPLIER = '" + tfIDSupp.getText() + "'";

            int btnDialog = JOptionPane.YES_NO_OPTION;
            int rsDialog = JOptionPane.showConfirmDialog(this, "Yakin mau dihapus?", "PERINGATAN", btnDialog);
            if (rsDialog == 0) {
                st = conn.createStatement();
                st.executeUpdate(sql);
                JOptionPane.showMessageDialog(null, "Data terhapus!");
            } else {
            }

            clear();
            tampilSupp();

        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // Clear fields
        clear();
    }//GEN-LAST:event_btnResetActionPerformed

    private void tfSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfSearchActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:

    }//GEN-LAST:event_formWindowOpened

    private void tfSearchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfSearchKeyPressed
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("ID");
        model.addColumn("Nama");
        model.addColumn("Alamat");
        model.addColumn("No Telp");

        try {
            String sql = "SELECT * FROM SUPPLIER WHERE ID_SUPPLIER LIKE '%" + tfSearch.getText() + "%' OR NAMA_SUPPLIER LIKE '%" + tfSearch.getText() + "%' OR ALAMAT_SUPPLIER LIKE '%" + tfSearch.getText() + "%' OR NO_TELP_SUPPLIER LIKE '%" + tfSearch.getText() + "%'";
            st = conn.createStatement();
            rs = st.executeQuery(sql);

            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getString("ID_SUPPLIER"), rs.getString("NAMA_SUPPLIER"), rs.getString("ALAMAT_SUPPLIER"), rs.getString("NO_TELP_SUPPLIER")

                });
            }
            tbSupp.setModel(model);

        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_tfSearchKeyPressed

    private void tbSuppMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbSuppMouseClicked

        int baris = tbSupp.getSelectedRow();
        tfIDSupp.setText(tbSupp.getModel().getValueAt(baris, 0).toString());
        tfNamaSupp.setText(tbSupp.getModel().getValueAt(baris, 1).toString());
        tfAlamatSupp.setText(tbSupp.getModel().getValueAt(baris, 2).toString());
        tfNoSupp.setText(tbSupp.getModel().getValueAt(baris, 3).toString());
    }//GEN-LAST:event_tbSuppMouseClicked

    private void btnSimpanCustActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanCustActionPerformed
        // Menyimpan Cust
        try {
            String sql = "INSERT INTO PELANGGAN VALUES ('" + tfIDCust.getText() + "','" + tfNamaCust.getText() + "','" + tfAlamatCust.getText() + "','" + tfNoCust.getText() + "')";
            st = conn.createStatement();
            st.executeUpdate(sql);
            JOptionPane.showMessageDialog(null, "Simpan Berhasil!");
            clear();
            tampilCust();

        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_btnSimpanCustActionPerformed

    private void tfIDCustActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfIDCustActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfIDCustActionPerformed

    private void btnUbahCustActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahCustActionPerformed

        // Merubah Cust
        try {
            String sql = "UPDATE PELANGGAN SET NAMA_PELANGGAN = '" + tfNamaCust.getText() + "', ALAMAT_PELANGGAN = '" + tfAlamatCust.getText() + "', NO_TELP_PELANGGAN = '" + tfNoCust.getText() + "' WHERE ID_PELANGGAN = '" + tfIDCust.getText() + "'";
            st = conn.createStatement();
            st.executeUpdate(sql);
            JOptionPane.showMessageDialog(null, "Data telah diperbarui!");
            clear();
            tampilCust();

        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_btnUbahCustActionPerformed

    private void btnHapusCustActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusCustActionPerformed

        // Menghapus Cust
        try {
            String sql = "DELETE FROM PELANGGAN WHERE ID_PELANGGAN = '" + tfIDCust.getText() + "'";

            int btnDialog = JOptionPane.YES_NO_OPTION;
            int rsDialog = JOptionPane.showConfirmDialog(this, "Yakin mau dihapus?", "PERINGATAN", btnDialog);
            if (rsDialog == 0) {
                st = conn.createStatement();
                st.executeUpdate(sql);
                JOptionPane.showMessageDialog(null, "Data terhapus!");
            } else {
            }

            clear();
            tampilCust();

        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_btnHapusCustActionPerformed

    private void btnResetCustActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetCustActionPerformed
        // Clear Fields
        clear();
    }//GEN-LAST:event_btnResetCustActionPerformed

    private void tbCustMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbCustMouseClicked
        // agar saat klik, text muncul di text field
        int baris = tbCust.getSelectedRow();
        tfIDCust.setText(tbCust.getModel().getValueAt(baris, 0).toString());
        tfNamaCust.setText(tbCust.getModel().getValueAt(baris, 1).toString());
        tfAlamatCust.setText(tbCust.getModel().getValueAt(baris, 2).toString());
        tfNoCust.setText(tbCust.getModel().getValueAt(baris, 3).toString());
    }//GEN-LAST:event_tbCustMouseClicked

    private void tfSearchCustActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfSearchCustActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfSearchCustActionPerformed

    private void tfSearchCustKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfSearchCustKeyPressed
        // Search Cust
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("ID");
        model.addColumn("Nama");
        model.addColumn("Alamat");
        model.addColumn("No Telp");

        try {
            String sql = "SELECT * FROM PELANGGAN WHERE ID_PELANGGAN LIKE '%" + tfSearchCust.getText() + "%' OR NAMA_PELANGGAN LIKE '%" + tfSearchCust.getText() + "%' OR ALAMAT_PELANGGAN LIKE '%" + tfSearchCust.getText() + "%' OR NO_TELP_PELANGGAN LIKE '%" + tfSearchCust.getText() + "%'";
            st = conn.createStatement();
            rs = st.executeQuery(sql);

            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getString("ID_PELANGGAN"), rs.getString("NAMA_PELANGGAN"), rs.getString("ALAMAT_PELANGGAN"), rs.getString("NO_TELP_PELANGGAN")

                });
            }
            tbCust.setModel(model);

        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_tfSearchCustKeyPressed

    private void btnBeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBeliActionPerformed
        // remove panel
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();

        // add panel
        mainPanel.add(panelTB);
        mainPanel.repaint();
        mainPanel.revalidate();
    }//GEN-LAST:event_btnBeliActionPerformed

    private void btnSimpanBukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanBukuActionPerformed
        // Menyimpan data buku
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy/MM/dd");
        String date = sdf.format(tanggalmasuk.getDate());

        int year;
        year = tahunterbit.getYear(); // TAHUN 

        try {
            String sql = "INSERT INTO BUKU VALUES ('" + tfIDBuku.getText() + "','"
                    + tfIDPenulis.getText() + "','"
                    + tfIDPenerbit.getText() + "', null, '"
                    + tfIDKategori.getText() + "','"
                    + tfISBN.getText() + "','"
                    + tfJudulBuku.getText() + "','"
                    + year + "','" //tahun
                    + date + "','" //tgl masuk
                    + tfStok.getText() + "','" //stok
                    + tfRak.getText() + "','" //rak
                    + tfHarga.getText() + "')";  //harga
            st = conn.createStatement();
            st.executeUpdate(sql);

            JOptionPane.showMessageDialog(null, "Simpan Berhasil!");
            clear();
            tampilBuku();

        } catch (Exception e) {
            System.out.println(e.getMessage());
        }

    }//GEN-LAST:event_btnSimpanBukuActionPerformed

    private void btnUbahBukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahBukuActionPerformed
        // Merubah Buku
        try {
            String sql = "UPDATE BUKU SET NAMA_PELANGGAN = '"
                    + tfIDPenulis.getText() + "','"
                    + tfIDPenerbit.getText() + "', null, '"
                    + tfIDKategori.getText() + "','"
                    + tfISBN.getText() + "','"
                    + tfJudulBuku.getText() + "','"
                    //                    + year + "','" //tahun
                    //                    + date + "','" //tgl masuk
                    + tfStok.getText() + "','" //stok
                    + tfRak.getText() + "','" //rak
                    + tfHarga.getText() + "')" //harga
                    + "' WHERE ID_BUKU = '" + tfIDBuku.getText() + "'";
            st = conn.createStatement();
            st.executeUpdate(sql);
            JOptionPane.showMessageDialog(null, "Data telah diperbarui!");
            clear();
            tampilBuku();

        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_btnUbahBukuActionPerformed

    private void btnHapusBukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusBukuActionPerformed

        // Menghapus Buku
        try {
            String sql = "DELETE FROM BUKU WHERE ID_BUKU = '" + tfIDBuku.getText() + "'";

            int btnDialog = JOptionPane.YES_NO_OPTION;
            int rsDialog = JOptionPane.showConfirmDialog(this, "Yakin mau dihapus?", "PERINGATAN", btnDialog);
            if (rsDialog == 0) {
                st = conn.createStatement();
                st.executeUpdate(sql);
                JOptionPane.showMessageDialog(null, "Data terhapus!");
            } else {
            }

            clear();
            tampilBuku();

        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_btnHapusBukuActionPerformed

    private void btnResetBukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetBukuActionPerformed
        // Clear text field
        clear();
    }//GEN-LAST:event_btnResetBukuActionPerformed

    private void tbBukuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbBukuMouseClicked

        int baris = tbBuku.getSelectedRow();
        // tanggalmasuk.setDate((Date) tbBuku.getModel().getValueAt(baris, 0));
        //tahunterbit.setYear((int) tbBuku.getModel().getValueAt(baris, 9));
        tfIDBuku.setText(tbBuku.getModel().getValueAt(baris, 1).toString());
        tfIDPenulis.setText(tbBuku.getModel().getValueAt(baris, 4).toString());
        tfIDPenerbit.setText(tbBuku.getModel().getValueAt(baris, 8).toString());
        tfIDKategori.setText(tbBuku.getModel().getValueAt(baris, 7).toString());
        tfISBN.setText(tbBuku.getModel().getValueAt(baris, 2).toString());
        tfJudulBuku.setText(tbBuku.getModel().getValueAt(baris, 3).toString());
        tfStok.setText(tbBuku.getModel().getValueAt(baris, 5).toString());
        tfHarga.setText(tbBuku.getModel().getValueAt(baris, 6).toString());
        tfRak.setText(tbBuku.getModel().getValueAt(baris, 10).toString());
    }//GEN-LAST:event_tbBukuMouseClicked

    private void tfSearchBukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfSearchBukuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfSearchBukuActionPerformed

    private void tfSearchBukuKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfSearchBukuKeyPressed
        // Search Buku

        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("Tanggal Masuk");
        model.addColumn("ID BUKU");
        model.addColumn("ISBN");
        model.addColumn("Judul");
        model.addColumn("Penulis");
        model.addColumn("Stok");
        model.addColumn("Harga");
        model.addColumn("Kategori");
        model.addColumn("Penerbit");
        model.addColumn("Tahun Terbit");
        model.addColumn("Rak");
        try {
            String sql = "SELECT * FROM BUKU WHERE ID_BUKU LIKE '%" + tfSearchBuku.getText() + "%' OR ISBN LIKE '%" + tfSearch.getText() + "%' OR JUDUL LIKE '%" + tfSearch.getText() + "%' OR PENULIS LIKE '%" + tfSearch.getText() + "%'";
            st = conn.createStatement();
            rs = st.executeQuery(sql);

            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getString("TANGGAL_MASUK"), rs.getString("ID_BUKU"), rs.getString("ISBN"), rs.getString("JUDUL"), rs.getString("ID_PENULIS"), rs.getString("STOK"), rs.getString("HARGA"), rs.getString("ID_KATEGORI"), rs.getString("ID_PENERBIT"), rs.getString("TAHUN_TERBIT"), rs.getString("RAK")

                });
            }
            tbSupp.setModel(model);

        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_tfSearchBukuKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(bpKasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(bpKasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(bpKasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(bpKasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new bpKasir().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel HEAD;
    private javax.swing.JLabel ID;
    private javax.swing.JPanel LEFT;
    private javax.swing.JButton btnBeli;
    private javax.swing.JButton btnBuku;
    private javax.swing.JButton btnCust;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnHapusBuku;
    private javax.swing.JButton btnHapusCust;
    private javax.swing.JButton btnJual;
    private javax.swing.JButton btnReport;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnResetBuku;
    private javax.swing.JButton btnResetCust;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnSimpanBuku;
    private javax.swing.JButton btnSimpanCust;
    private javax.swing.JButton btnSupp;
    private javax.swing.JButton btnUbah;
    private javax.swing.JButton btnUbahBuku;
    private javax.swing.JButton btnUbahCust;
    private javax.swing.JLabel head;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lAlamat;
    private javax.swing.JLabel lAlamatCust;
    private javax.swing.JLabel lAlamatCust1;
    private javax.swing.JLabel lBuku;
    private javax.swing.JLabel lCust;
    private javax.swing.JLabel lID;
    private javax.swing.JLabel lIDBuku;
    private javax.swing.JLabel lIDBuku1;
    private javax.swing.JLabel lIDCust;
    private javax.swing.JLabel lNama;
    private javax.swing.JLabel lNamaCust;
    private javax.swing.JLabel lNamaCust1;
    private javax.swing.JLabel lNo;
    private javax.swing.JLabel lNoCust;
    private javax.swing.JLabel lNoCust1;
    private javax.swing.JLabel lNoCust2;
    private javax.swing.JLabel lNoCust3;
    private javax.swing.JLabel lNoCust4;
    private javax.swing.JLabel lNoCust5;
    private javax.swing.JLabel lNoCust6;
    private javax.swing.JLabel lNoCust7;
    private javax.swing.JLabel lReport;
    private javax.swing.JLabel lSupp;
    private javax.swing.JLabel lTB;
    private javax.swing.JLabel lTJ;
    private javax.swing.JButton logout;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel panelBuku;
    private javax.swing.JPanel panelCust;
    private javax.swing.JPanel panelReport;
    private javax.swing.JPanel panelSupp;
    private javax.swing.JPanel panelTB;
    private javax.swing.JPanel panelTJ;
    private com.toedter.calendar.JYearChooser tahunterbit;
    private com.toedter.calendar.JDateChooser tanggalmasuk;
    private javax.swing.JTable tbBuku;
    private javax.swing.JTable tbCust;
    private javax.swing.JTable tbSupp;
    private javax.swing.JTextArea tfAlamatCust;
    private javax.swing.JTextArea tfAlamatSupp;
    private javax.swing.JTextField tfHarga;
    private javax.swing.JTextField tfIDBuku;
    private javax.swing.JTextField tfIDCust;
    private javax.swing.JTextField tfIDKategori;
    private javax.swing.JTextField tfIDPenerbit;
    private javax.swing.JTextField tfIDPenulis;
    private javax.swing.JTextField tfIDSupp;
    private javax.swing.JTextField tfISBN;
    private javax.swing.JTextField tfJudulBuku;
    private javax.swing.JTextField tfNamaCust;
    private javax.swing.JTextField tfNamaSupp;
    private javax.swing.JTextField tfNoCust;
    private javax.swing.JTextField tfNoSupp;
    private javax.swing.JTextField tfRak;
    private javax.swing.JTextField tfSearch;
    private javax.swing.JTextField tfSearchBuku;
    private javax.swing.JTextField tfSearchCust;
    private javax.swing.JTextField tfStok;
    // End of variables declaration//GEN-END:variables
}
